env:
  TERM: xterm-256color
  WINIT_X11_SCALE_FACTOR: "1.0"

window:
  padding:
    x: 2
    y: 2

scrolling:
  history: 10000

font:
  normal:
    family: Hack Nerd Font
    style: Regular
  bold:
    family: Hack Nerd Font
    style: Bold
  italic:
    family: Hack Nerd Font
    style: Italic
  size: 10.0
  offset:
    x: 0

background_opacity: 0.7

cursor:
  style: Block
  unfocused_hollow: true

live_config_reload: true

mouse:
  hide_when_typing: true

key_bindings:
  - { key: K, mods: Alt, action: ScrollLineUp }
  - { key: J, mods: Alt, action: ScrollLineDown }

# BEGIN ACE
colors:
  primary:
    background: '0x282828'
    foreground: '0xa89984'
  cursor:
    text:       '0x282828'
    cursor:     '0xa89984'
  normal:
    black:      '0x282828'
    red:        '0xcc241d'
    green:      '0xd79921'
    yellow:     '0xb58900'
    blue:       '0x458588'
    magenta:    '0xb16286'
    cyan:       '0x689d6a'
    white:      '0xa89984'
  bright:
    black:      '0x928374'
    red:        '0xcc241d'
    green:      '0xd79921'
    yellow:     '0xb58900'
    blue:       '0x458588'
    magenta:    '0xb16286'
    cyan:       '0x689d6a'
    white:      '0xa89984'

# END ACE
