env:
  TERM: xterm-256color

window:
  padding:
    x: 2
    y: 2

scrolling:
  history: 10000

font:
  normal:
    family: Hack Nerd Font
    style: Regular
  bold:
    family: Hack Nerd Font
    style: Bold
  italic:
    family: Hack Nerd Font
    style: Italic
  size: 10.0
  offset:
    x: 0

background_opacity: 0.7

cursor:
  style: Block
  unfocused_hollow: true

live_config_reload: true

mouse:
  hide_when_typing: true

key_bindings:
  - { key: K, mods: Alt, action: ScrollLineUp }
  - { key: J, mods: Alt, action: ScrollLineDown }

# BEGIN ACE
colors:
  primary:
    background: '0x0f0d10'
    foreground: '0xded5d7'
  cursor:
    text:       '0x0f0d10'
    cursor:     '0xded5d7'
  normal:
    black:      '0x0f0d10'
    red:        '0xAC8D6D'
    green:      '0xC6A178'
    yellow:     '0x78798D'
    blue:       '0xB09E96'
    magenta:    '0xCDB498'
    cyan:       '0xE5CFAC'
    white:      '0xded5d7'
  bright:
    black:      '0x9b9596'
    red:        '0xAC8D6D'
    green:      '0xC6A178'
    yellow:     '0x78798D'
    blue:       '0xB09E96'
    magenta:    '0xCDB498'
    cyan:       '0xE5CFAC'
    white:      '0xded5d7'

# END ACE
