env:
  TERM: xterm-256color

window:
  padding:
    x: 2
    y: 2

scrolling:
  history: 10000

font:
  normal:
    family: Hack Nerd Font
    style: Regular
  bold:
    family: Hack Nerd Font
    style: Bold
  italic:
    family: Hack Nerd Font
    style: Italic
  size: 10.0
  offset:
    x: 0

background_opacity: 0.7

cursor:
  style: Block
  unfocused_hollow: true

live_config_reload: true

mouse:
  hide_when_typing: true

key_bindings:
  - { key: K, mods: Alt, action: ScrollLineUp }
  - { key: J, mods: Alt, action: ScrollLineDown }

# BEGIN ACE
colors:
  primary:
    background: '0x0c0a0c'
    foreground: '0xc29fa5'
  cursor:
    text:       '0x0c0a0c'
    cursor:     '0xc29fa5'
  normal:
    black:      '0x0c0a0c'
    red:        '0x6C3B44'
    green:      '0x32464A'
    yellow:     '0x71464E'
    blue:       '0x931D31'
    magenta:    '0x9D3747'
    cyan:       '0xD93E58'
    white:      '0xc29fa5'
  bright:
    black:      '0x876f73'
    red:        '0x6C3B44'
    green:      '0x32464A'
    yellow:     '0x71464E'
    blue:       '0x931D31'
    magenta:    '0x9D3747'
    cyan:       '0xD93E58'
    white:      '0xc29fa5'

# END ACE
